### ISSUE TITLE
Doubts about the Haptico plugin

### ISSUE THREAD

**Issue by MonseRH** [sindemcos/Haptico#3]
Hi, I am a master degree student, I am working in the development of a virtual environment with Unreal Engine and I am using the Haptico plugin, but I have some questions related to the blueprint "Get Haptic Device Linear Velocity" and the "Get Haptic Device Angular Velocity", the last is the velocity related to the motors?. I hope you can contact me, my email is mon.r.h@hotmail.com

**Comment by sindemcos** [comment]
Hi, Yes these are the current velocities of the pen in x,y and z (as 3d vector). Units are in m/s.
